- name: Install dependencies
  apt:
    pkg:
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - python3
      - cargo
    state: present
    autoremove: yes
    update_cache: yes

- name: Install Alacritty
  shell:
    cmd: "cargo install alacritty"