window:
  padding:
    x: 15
    y: 15

font:
  normal:
    family: "Hack Nerd Font"
    style: Bold
  bold: 
    family: "Hack Nerd Font"
    style: Bold
  italic:
    family: "Hack Nerd Font"
    style: "Light Italic"
  size: 10

colors:
  primary:
    background: '0x002b36'
    foreground: '0xcfc9c2'
  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xffffff'
    cursor: '0x4d4d4c'
  # Normal colors
  normal:
    black:   '0x002b36'
    red:     '0xd30102'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0xd33682'
    cyan:    '0x2aa198'
    white:   '0xeee8d5'
  # Bright colors
  bright:
    black:   '0x073642'
    red:     '0xcb4b16'
    green:   '0x586e75'
    yellow:  '0x657b83'
    blue:    '0x839496'
    magenta: '0x6c71c4'
    cyan:    '0x93a1a1'
    white:   '0xfdf6e3'

env:
  TERM: xterm-256color