# shell:
#   program: "C:\\Windows\\System32\\wsl.exe ~ -u hostile"

window:
  padding:
    x: 15
    y: 15

font:
  normal:
    family: "Hack Nerd Font"
    style: Bold
  bold:
    family: "Hack Nerd Font"
    style: Bold
  italic:
    family: "Hack Nerd Font"
    style: "Light Italic"
  size: 10
colors:
  primary:
    background: '0x1a1b26'
    foreground: '0xd5d6db'
  cursor:
    text: '0xd5d6db'
    cursor: '0x5A9CA1'
  normal:
    black:   '0x1a1b26'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x73daca'
    white:   '0xe4e4e4'
  bright:
    black:   '0x414868'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x73daca'
    white:   '0xe4e4e4'

env:
  TERM: xterm-256color