format = """
[┌](bright-green)$username$jobs$time$cmd_duration$status
[└](bright-green)$directory$git_branch$git_status$python
 $character
"""

[username]
format = '[─\[](bright-green)[$user]($style)[\]]( bright-green)'
style_user = 'cyan'
style_root = ' bright-red'
disabled = false
show_always = true

[time]
format = '[───\[]( bright-green)[$time]($style)[\]]( bright-green)'
style = 'bright-green'
disabled = false

[cmd_duration]
format = '[───\[]( bright-green)[$duration]($style)[\]]( bright-green)'
style = ' bright-green'

[directory]
format = '[─\[]( bright-green)[ ]($style) [$path]($style)[\]]( bright-green)'
style = 'cyan'

[git_branch]
format = '[─\[]( bright-green)[$symbol $branch]($style)[\]](bright-green)'
symbol = ''
style = ' green'
truncation_length = 30

[git_status]
format = '([─\[]( bright-green)[$all_status]($style)[\]](bright-green))'
style = 'bright-red'

[python]
format = '[─\[]( bright-green)[$symbol ($virtualenv )$version]($style)[\]](bright-green)'
symbol = ''
style = 'bright-cyan'

[status]
format = '[───\[]( bright-green)[$symbol $status]($style)[\]]( bright-green)'
symbol = ''
style = 'bright-red'
disabled = false

[character]
success_symbol = "[]( bright-green) "
error_symbol = "[]( bright-green) "

[jobs]
format = '[───\[]( bright-green)[$symbol $number]($style)[\]]( bright-green)'
number_threshold = 1
style = 'bright-green'
symbol = ''
