right_format = "$python$golang$nodejs"

format = """
$username$directory$git_branch$git_status$jobs$cmd_duration

$status$character
"""

[username]
format = '[](bright-black)[ $user]($style)[ ](bright-black)'
style_user = 'bg:bright-black fg:cyan'
style_root = 'bg:bright-black fg:bright-red'
disabled = false
show_always = true

[cmd_duration]
format = '[](bright-black)[祥$duration]($style)[ ](bright-black)'
style = 'bg:bright-black fg:blue'

[directory]
format = '[](bright-black)[ $path]($style)[ ](bright-black)'
style = 'bg:bright-black fg:green'

[git_branch]
format = '[](bright-black)[$symbol $branch]($style)'
symbol = ''
style = 'bg:bright-black fg:bright-green'
truncation_length = 30

[git_status]
format = '[ $all_status]($style)[ ](bright-black)'
style = 'bg:bright-black fg:bright-red'

[status]
format = '[](bright-black)[$symbol $status]($style)'
symbol = ''
style = 'fg:bright-red bg:bright-black'
disabled = false

[character]
success_symbol = '[](bright-black)[](bg:bright-black fg:green)[](bright-black)'
error_symbol = '[ ](bg:bright-black fg:green)[](bright-black)'

[jobs]
format = '[](bright-black)[$symbol $number]($style)[ ](bright-black)'
number_threshold = 1
style = 'fg:bright-yellow bg:bright-black'
symbol = ''

# Languages

[python]
format = '[](bright-black)[$symbol ($virtualenv )$version]($style)[ ](bright-black)'
symbol = ''
style = 'fg:yellow bg:bright-black'

[golang]
format = '[](bright-black)[$symbol $version]($style)[ ](bright-black)'
symbol = ''
style = 'fg:blue bg:bright-black'

[nodejs]
format = '[](bright-black)[$symbol $version]($style)[ ](bright-black)'
symbol = ''
style = 'fg:green bg:bright-black'